version: '3.7'
services:
  gateway:
    image: vtuanjs/api-gateway:v1
    restart: always
    volumes:
      - sv-gateway:/gateway
    ports:
      - "3000:3000"
  userapp:
    image: vtuanjs/user-manager:v1
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - sv-user:/user
    deploy: 
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    networks:
      - my-user
    depends_on: 
      - usermongo
    links: 
      - usermongo
  usermongo:
    image: mongo:latest
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=dbtest
    ports:
      - '27017:27017'
    networks:
      - my-user
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-user:/data
  productapp:
    image: vtuanjs/product-manager:v1
    restart: always
    volumes:
      - sv-product:/product
    ports:
      - "3002:3002"
    deploy: 
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    networks:
      - my-product
    depends_on: 
      - productmongo
    links: 
      - productmongo
  productmongo:
    image: mongo:latest
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=dbtest
    ports:
      - '27018:27017'
    networks:
      - my-product
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-product:/data
volumes:
  sv-gateway:
  sv-user:
  sv-product:
  db-user:
  db-product:
networks: 
  my-user:
    driver: overlay
  my-product:
    driver: overlay
    