version: "3.7"
services:
  product-manager:
    container_name: product-manager
    image: vtuanjs/product-manager
    restart: always
    build: .
    ports:
      - "3003:3001"
    env_file: 
      - .env
    networks: 
      - backend
  mongo:
    container_name: product-mongo
    image: mongo:4.2.1
    ports:
      - 27017:27017
    networks: 
      - backend
    env_file: 
      - .env
    environment:
      MONGO_INITDB_DATABASE: "dbtest"
      MONGO_INITDB_ROOT_USERNAME: "dbtest"
      MONGO_INITDB_ROOT_PASSWORD: "dbtest"
      MONGODB_USER: "dbtest"
      MONGODB_PASSWORD: "dbtest"
    volumes:
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - product-mongo-db:/data/db
      - product-mongo-backup:/backup
volumes:
  product-mongo-db:
  product-mongo-backup:
networks: 
  backend:

