version: "3.7"
services:
  product:
    container_name: product-service
    restart: always
    build: .
    ports:
      - "3003:3001"
    networks: 
      - backend
  mongo:
    container_name: product-mongo
    image: mongo:4.2.1
    ports:
      - 27017:27017
    networks: 
      - backend
    environment:
      MONGO_INITDB_DATABASE: "dbtest"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - product-mongo-db:/data/db
      - product-mongo-backup:/backup
volumes:
  product-mongo-db:
  product-mongo-backup:
networks: 
  backend:

