version: "3.7"
services:
  user:
    image: vtuanjs/user-manager
    ports:
      - "3002:3001"
    env_file: 
      - .env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: "0.25"
          memory: 50M
  mongo:
    image: mongo:4.2.1
    ports:
      - 27017:27017
    networks: 
      - backend
    env_file: 
      - .env
    environment:
      MONGO_INITDB_DATABASE: "dbtest"
      MONGODB_USER_NAME: "${MONGODB_USER_NAME}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - user-mongo-db:/data/db
      - user-mongo-backup:/backup
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: "0.25"
          memory: 50M
volumes:
  user-mongo-db:
  user-mongo-backup:
networks:
  backend:

